const PEOPLE = {
  "saumil-tripathi": { name: "Saumil Tripathi", sub: "tal by grapevine · Founder", why: "founder: grapevine | meet tal at tal.af | ex google, youtube", pfp: "pfps/2f8154862097.jpg", cat: "founders-cxos", votes: 950 },
  "sanchit-tripathi": { name: "Sanchit Tripathi", sub: "tal by grapevine · Engineer", why: "making tal funnier & less rude | go to tal.af", pfp: "pfps/ed729aa98f7f.jpg", cat: "eng", votes: 947 },
  "abhishek-jayaram": { name: "Abhishek Jayaram", sub: "tal (by Grapevine) · Engineer", why: "helping tal find a job for himself | visit tal.af", pfp: "pfps/440f37aca75a.jpg", cat: "eng", votes: 944 },
  "rishikesh-ganguly": { name: "Rishikesh Ganguly", sub: "tal (by Grapevine) · Engineer", why: "tal's fixer", pfp: "pfps/a7b5ca006e17.jpg", cat: "eng", votes: 941 },
  "tushar-n": { name: "Tushar N.", sub: "tal (by Grapevine) · Product Lead", why: "tal's brain since v0.0.1. he's on v47 now. I aged.", pfp: "pfps/35840d09a6dc.jpg", cat: "product", votes: 938 },
  "jainam-tal-sania": { name: "Jainam TAL-sania", sub: "tal (by Grapevine) · Cofounder", why: "built tal. he wants a salary now. cofounder - tal, grapevine", pfp: "pfps/274f42dfca36.jpg", cat: "founders-cxos", votes: 935 },
  "shreeyash-dharmadhikari": { name: "Shreeyash Dharmadhikari", sub: "Tal - AI Talent Agent · Cofounder", why: "made tal the most attractive fox | Founder - Grapevine | ex-InMobi", pfp: "pfps/7e2890c5331e.jpg", cat: "founders-cxos", votes: 932 },
  "souvik-kar-mahapatra": { name: "Souvik Kar Mahapatra", sub: "Tal - AI Talent Agent · CTO", why: "architected tal. he acts like he's self-taught.", pfp: "pfps/a2dde43c4f08.jpg", cat: "eng", votes: 200 },
  "yash-shah": { name: "Yash Shah", sub: "tal by grapevine · Growth", why: "spending money so tal gets famous", pfp: "pfps/fcdb23833d9d.jpg", cat: "founders-cxos", votes: 197 },
  "pari-vashisht": { name: "Pari Vashisht", sub: "tal by grapevine · Growth", why: "tal's publicist :) | growth & biz @ grapevine", pfp: "pfps/af54cee63822.jpg", cat: "founders-cxos", votes: 194 },
  "prabhav-pandey": { name: "Prabhav Pandey", sub: "Tal - AI Talent Agent · Brand", why: "making tal famous | ex-bain, built life2.club", pfp: "pfps/6287d7b72894.jpg", cat: "founders-cxos", votes: 191 },
  "dhwani-dodia": { name: "Dhwani Dodia", sub: "tal by grapevine · Designer", why: "tal's stylist | product designer at grapevine | ex - please see", pfp: "pfps/52c6c6a20a03.jpg", cat: "product", votes: 188 },
  "akshat-kumar": { name: "Akshat Kumar", sub: "tal (by Grapevine) · Product", why: "been breaking tal since user #3 | product @tal, gv", pfp: "pfps/340af05c1579.jpg", cat: "product", votes: 185 },
  "megh-bari": { name: "Megh Bari", sub: "tal by grapevine · Engineer", why: "Build tal a home on the internet | created patterncraft.fun | cooking @tal (by Grapevine)", pfp: "pfps/0395c200a4af.jpg", cat: "eng", votes: 182 },
  "kartikay-gupta": { name: "Kartikay Gupta", sub: "tal by grapevine · Business", why: "biz @ gv | scrolling linkedin to see if you met tal", pfp: "pfps/c0b8a17fd8aa.jpg", cat: "founders-cxos", votes: 179 },
  "gaurika-jindal": { name: "Gaurika Jindal", sub: "Tal - AI Talent Agent · Growth", why: "Building Tal by Grapevine", pfp: "pfps/407f5037f584.jpg", cat: "founders-cxos", votes: 176 },
  "yashwardhan-singh": { name: "Yashwardhan Singh", sub: "Tal - AI Talent Agent · Cofounder", why: "Co-Founder of PinkMatter, BMS", pfp: "pfps/4356859bc7f2.jpg", cat: "founders-cxos", votes: 173 },
  "bigyan-patel": { name: "Bigyan Patel", sub: "tal (by Grapevine) · Engineer", why: "bringing tal to life", pfp: "pfps/a524325409d0.jpg", cat: "eng", votes: 170 },
  "krish-srivastava": { name: "Krish Srivastava", sub: "Tal - AI Talent Agent · Engineer", why: "reason why tal remembers you!", pfp: "pfps/4e0994e860dc.jpg", cat: "eng", votes: 167 },
  "arshdeep-singh": { name: "Arshdeep Singh", sub: "Tal - AI Talent Agent · Engineer", why: "IIT Roorkee '27 | LFX'25 @WasmEdge | Developer at SDSLabs", pfp: "pfps/ac21c6b9eab3.jpg", cat: "eng", votes: 164 },
  "monil-mehta": { name: "Monil Mehta", sub: "tal (by Grapevine) · Engineer", why: "the reason tal didn't crash today | engineering @ grapevine | turning ideas into shippe...", pfp: "pfps/94ab9eda800e.jpg", cat: "eng", votes: 161 },
};
